# Uncomment the next line to define a global platform for your project
platform :ios, '13'

target 'Flash Chat iOS13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flash Chat iOS13
  pod 'CLTypingLabel'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

  # change current editing textfield position based on soft keyboard
  # pod 'IQKeyboardManagerSwift'

end
